const PROJECTS=[
 ['Tickblaze','Trading Technology · WordPress','https://tickblaze.com/','#f04438'],['PropShopTrader','Trading Platform · WordPress','https://propshoptrader.com/','#3562ff'],['Hat Creek Training','Training Platform · WordPress','https://www.hatcreektraining.com/','#f7a62d'],['MI Furniture','Ecommerce · WordPress','https://mi-furniture.co.uk/','#9d5cff'],['Gennari Partners','Coaching System · GHL','https://gennaripartners.com/home','#19a97d'],['Elevated Roofing','Lead Generation · GHL','https://elevatedroofingsolutions.ca/home','#ef4b71'],['School of Threaded Arts','Education Funnel','https://schoolofthreadedarts.com/cksr','#ff713c'],['Her Influence Academy','Masterclass Funnel','https://blueprint.herinfluenceacademy.com/','#6f4df6']
];
const projectRoot=document.querySelector('#projects');
projectRoot.innerHTML=PROJECTS.map(([name,cat,url,color],i)=>`<a class="project reveal" href="${url}" target="_blank" rel="noopener" style="--accent:${color}"><div class="project-card"><span class="project-monogram">${name.split(/\s/).map(x=>x[0]).slice(0,2).join('')}</span></div><div class="project-meta"><div><p>0${i+1} / SELECTED PROJECT</p><h3>${name}</h3></div><p>${cat} ↗</p></div></a>`).join('');

const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');let mx=0,my=0,rx=0,ry=0;
addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});
(function cursor(){rx+=(mx-rx)*.13;ry+=(my-ry)*.13;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(cursor)})();
document.querySelectorAll('a,.service,.project').forEach(x=>{x.onmouseenter=()=>ring.classList.add('big');x.onmouseleave=()=>ring.classList.remove('big')});
addEventListener('scroll',()=>{document.querySelector('#progress').style.width=scrollY/(document.documentElement.scrollHeight-innerHeight)*100+'%'});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal,.split').forEach(x=>io.observe(x));
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.13}px,${(e.clientY-r.top-r.height/2)*.13}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});

function canvasScene(canvas,mode){const ctx=canvas.getContext('2d');let w,h,dpr,mouseX=0,mouseY=0,pts=[];function size(){dpr=Math.min(devicePixelRatio,2);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const count=mode==='hero'?170:90;pts=Array.from({length:count},(_,i)=>{const a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1),r=(mode==='orb'?90:Math.min(w,h)*(.18+Math.random()*.15));return{x:r*Math.sin(b)*Math.cos(a),y:r*Math.cos(b),z:r*Math.sin(b)*Math.sin(a),a,i}})}
  addEventListener('resize',size);size();canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouseX=(e.clientX-r.left-r.width/2)/r.width;mouseY=(e.clientY-r.top-r.height/2)/r.height});let t=0;
  function draw(){t+=.004;ctx.clearRect(0,0,w,h);const cx=mode==='hero'?w*.72:w/2,cy=mode==='hero'?h*.52:h/2,rot=t+mouseX*.45,tilt=.35+mouseY*.25;const projected=pts.map(p=>{let x=p.x*Math.cos(rot)-p.z*Math.sin(rot),z=p.x*Math.sin(rot)+p.z*Math.cos(rot),y=p.y*Math.cos(tilt)-z*Math.sin(tilt);z=p.y*Math.sin(tilt)+z*Math.cos(tilt);const s=360/(360+z);return{x:cx+x*s,y:cy+y*s,z,s}});projected.forEach((p,i)=>{if(i%3===0){const q=projected[(i+7)%projected.length];const dist=Math.hypot(p.x-q.x,p.y-q.y);if(dist<(mode==='orb'?90:180)){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=`rgba(240,68,56,${.11*(1-dist/(mode==='orb'?90:180))})`;ctx.stroke()}}ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.45,1.7*p.s),0,7);ctx.fillStyle=`rgba(${mode==='orb'?'20,20,20':'255,112,98'},${.22+.5*p.s})`;ctx.fill()});requestAnimationFrame(draw)}draw()}
canvasScene(document.querySelector('#hero3d'),'hero');canvasScene(document.querySelector('#orb3d'),'orb');canvasScene(document.querySelector('#contact3d'),'contact');
const counterIO=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;document.querySelectorAll('[data-count]').forEach(el=>{const n=+el.dataset.count;let v=0;const timer=setInterval(()=>{v=Math.min(n,v+Math.max(1,Math.ceil(n/55)));el.textContent=v;if(v>=n)clearInterval(timer)},20)});counterIO.disconnect()}),{threshold:.4});counterIO.observe(document.querySelector('.numbers'));
addEventListener('mousemove',e=>{document.querySelectorAll('[data-depth]').forEach(x=>{const d=+x.dataset.depth;x.style.transform=`translate(${(e.clientX-innerWidth/2)*d}px,${(e.clientY-innerHeight/2)*d}px)`})});
